name: MassiveQC
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python >=3.7
  - sklearn
  - shap
  - pysradb
  - xopen
  - NumPy
  - Pandas >=1.3.2
  - pyarrow
  - more_itertools
  - tqdm
  - atropos
  - fastq-screen
  - hisat2
  - samtools
  - bamtools
  - subread
  - MassiveQC